[package]
name = "boxcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
wgpu = "0.12.0"
winit = "0.26.1"
nalgebra = "0.31.0"
rapier3d = "0.11.1"
imgui = "0.8.2"
imgui-winit-support = { version = "0.8.2", default-features = false, features = ["winit-26"] }
imgui-wgpu = "0.19.0"
log = "0.4"
env_logger = "0.9"
pollster = "0.2.5"
legion = "0.4.0"